# Generated by Django 5.1.5 on 2025-01-21 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_credential_education_experience_interests_skills'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Credential',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Interests',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
